#ifndef REMASTER_EMERALD_SCRIPT_HOST_H
#define REMASTER_EMERALD_SCRIPT_HOST_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef enum RemasterEmeraldScriptRequestType {
    REMASTER_EMERALD_SCRIPT_REQUEST_NONE = 0,
    REMASTER_EMERALD_SCRIPT_REQUEST_WAIT_STATE,
    REMASTER_EMERALD_SCRIPT_REQUEST_MESSAGE,
    REMASTER_EMERALD_SCRIPT_REQUEST_CHOICE,
    REMASTER_EMERALD_SCRIPT_REQUEST_DELAY,
    REMASTER_EMERALD_SCRIPT_REQUEST_SOUND,
    REMASTER_EMERALD_SCRIPT_REQUEST_FANFARE,
    REMASTER_EMERALD_SCRIPT_REQUEST_BGM,
    REMASTER_EMERALD_SCRIPT_REQUEST_FADE,
    REMASTER_EMERALD_SCRIPT_REQUEST_DOOR,
    REMASTER_EMERALD_SCRIPT_REQUEST_OBJECT,
    REMASTER_EMERALD_SCRIPT_REQUEST_MOVEMENT,
    REMASTER_EMERALD_SCRIPT_REQUEST_WARP,
    REMASTER_EMERALD_SCRIPT_REQUEST_STARTER_SELECTION,
    REMASTER_EMERALD_SCRIPT_REQUEST_DOMAIN,
    REMASTER_EMERALD_SCRIPT_REQUEST_SPECIAL,
    REMASTER_EMERALD_SCRIPT_REQUEST_WORLD
} RemasterEmeraldScriptRequestType;

typedef enum RemasterEmeraldScriptObjectAction {
    REMASTER_EMERALD_SCRIPT_OBJECT_ADD = 1,
    REMASTER_EMERALD_SCRIPT_OBJECT_REMOVE,
    REMASTER_EMERALD_SCRIPT_OBJECT_SHOW,
    REMASTER_EMERALD_SCRIPT_OBJECT_HIDE,
    REMASTER_EMERALD_SCRIPT_OBJECT_SET_XY,
    REMASTER_EMERALD_SCRIPT_OBJECT_TURN,
    REMASTER_EMERALD_SCRIPT_OBJECT_FACE_PLAYER
} RemasterEmeraldScriptObjectAction;

typedef enum RemasterEmeraldScriptMovementAction {
    REMASTER_EMERALD_SCRIPT_MOVEMENT_START = 1,
    REMASTER_EMERALD_SCRIPT_MOVEMENT_WAIT
} RemasterEmeraldScriptMovementAction;

typedef enum RemasterEmeraldScriptMessageAction {
    REMASTER_EMERALD_SCRIPT_MESSAGE_SHOW = 1,
    REMASTER_EMERALD_SCRIPT_MESSAGE_CLOSE,
    REMASTER_EMERALD_SCRIPT_MESSAGE_WAIT
} RemasterEmeraldScriptMessageAction;

typedef enum RemasterEmeraldScriptAsyncAction {
    REMASTER_EMERALD_SCRIPT_ASYNC_START = 1,
    REMASTER_EMERALD_SCRIPT_ASYNC_WAIT
} RemasterEmeraldScriptAsyncAction;

typedef enum RemasterEmeraldScriptDoorAction {
    REMASTER_EMERALD_SCRIPT_DOOR_OPEN = 1,
    REMASTER_EMERALD_SCRIPT_DOOR_CLOSE,
    REMASTER_EMERALD_SCRIPT_DOOR_WAIT
} RemasterEmeraldScriptDoorAction;

typedef enum RemasterEmeraldScriptWorldAction {
    REMASTER_EMERALD_SCRIPT_WORLD_LOCK = 1,
    REMASTER_EMERALD_SCRIPT_WORLD_LOCK_ALL,
    REMASTER_EMERALD_SCRIPT_WORLD_RELEASE,
    REMASTER_EMERALD_SCRIPT_WORLD_RELEASE_ALL,
    REMASTER_EMERALD_SCRIPT_WORLD_SET_METATILE,
    REMASTER_EMERALD_SCRIPT_WORLD_SET_FOLLOWER,
    REMASTER_EMERALD_SCRIPT_WORLD_FOLLOWER_INTO_POKEBALL,
    REMASTER_EMERALD_SCRIPT_WORLD_UPDATE_FOLLOWER_GRAPHIC
} RemasterEmeraldScriptWorldAction;

typedef enum RemasterEmeraldScriptBgmAction {
    REMASTER_EMERALD_SCRIPT_BGM_PLAY = 1,
    REMASTER_EMERALD_SCRIPT_BGM_SAVE,
    REMASTER_EMERALD_SCRIPT_BGM_FADE_DEFAULT
} RemasterEmeraldScriptBgmAction;

typedef enum RemasterEmeraldScriptDomainAction {
    REMASTER_EMERALD_SCRIPT_DOMAIN_ACTION_ITEM_ADD = 1,
    REMASTER_EMERALD_SCRIPT_DOMAIN_ACTION_ITEM_REMOVE,
    REMASTER_EMERALD_SCRIPT_DOMAIN_ACTION_ITEM_CHECK,
    REMASTER_EMERALD_SCRIPT_DOMAIN_ACTION_ITEM_SPACE,
    REMASTER_EMERALD_SCRIPT_DOMAIN_ACTION_GIVE_MON,
    REMASTER_EMERALD_SCRIPT_DOMAIN_ACTION_HEAL_PARTY,
    REMASTER_EMERALD_SCRIPT_DOMAIN_ACTION_PARTY_SIZE,
    REMASTER_EMERALD_SCRIPT_DOMAIN_ACTION_INCREMENT_GAME_STAT,
    REMASTER_EMERALD_SCRIPT_DOMAIN_ACTION_BUFFER_LEAD_MON_SPECIES_NAME,
    REMASTER_EMERALD_SCRIPT_DOMAIN_ACTION_TRAINER_BATTLE_CONFIG,
    REMASTER_EMERALD_SCRIPT_DOMAIN_ACTION_TRAINER_BATTLE_START
} RemasterEmeraldScriptDomainAction;

typedef struct RemasterEmeraldScriptRequest {
    RemasterEmeraldScriptRequestType type;
    uint64_t sequence;
    uint32_t program_index;
    uint32_t pc;

    uint16_t action;
    uint16_t local_id;
    uint32_t map_id;
    const char *resource_id;
    int16_t x;
    int16_t y;
    uint16_t value_u16;
    uint32_t value_u32;
    uint16_t quantity;
    uint16_t result_var;
} RemasterEmeraldScriptRequest;

typedef struct RemasterEmeraldScriptCompletion {
    RemasterEmeraldScriptRequestType type;
    uint64_t sequence;
    uint16_t result_u16;
    uint16_t local_id;
    uint32_t map_id;
    uint8_t accepted;
} RemasterEmeraldScriptCompletion;

#ifdef __cplusplus
}
#endif

#endif
