#!/usr/bin/env python3
"""Deterministic display names/charmap; gameplay IDs remain core-owned."""
from pathlib import Path
import argparse
import json
import re
from build_r11_domain_catalog import DefineResolver, parse_charmap, parse_items

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / 'unreal/Source/PokemonEmeraldRemastered/RemasterUiCatalog.inl'


def build() -> str:
    vendor = ROOT / 'vendor/vanillaplus'
    resolver = DefineResolver(vendor / 'include')
    sections = {}
    for kind, filename, prefix in [('Species', 'species_names.h', 'SPECIES'),
                                   ('Move', 'move_names.h', 'MOVE')]:
        source = (vendor / 'src/data/text' / filename).read_text()
        pairs = re.findall(r'\[(' + prefix + r'_\w+)\]\s*=\s*_\("((?:[^"\\]|\\.)*)"\)', source)
        sections[kind] = {resolver.resolve(key): name for key, name in pairs}
    items, missing = parse_items(vendor, resolver)
    if missing:
        raise ValueError(f'unresolved item display fields: {missing}')
    sections['Item'] = {row['id']: row['name'] for row in items}
    regions = json.loads((vendor / 'src/data/region_map/region_map_sections.json').read_text())
    sections['Region'] = {resolver.resolve(row['map_section']): row['name']
                          for row in regions['map_sections']}
    lines = ['// Generated by tools/build_r9_ui_catalog.py. Do not edit.',
             '// Vanilla+ 70db90c9077aed1272e746fc2537d9f12b95a91c; display only.']
    for kind, pairs in sections.items():
        lines += [f'inline const char* {kind}Name(unsigned id) {{', '    switch (id) {']
        lines += [f'    case {key}: return {json.dumps(name, ensure_ascii=False)};'
                  for key, name in sorted(pairs.items())]
        lines += ['    default: return nullptr;', '    }', '}']
    # The source lists the Turkish/Latin page before Japanese aliases. First
    # byte binding wins; a reverse dict would silently replace Ğ with あ.
    chars = {}
    for key, value in parse_charmap(vendor).items():
        if len(key) == 1 and len(value) == 1 and value[0] != 255:
            chars.setdefault(value[0], key)
    lines += ['inline const char* NicknameGlyph(unsigned byte) {', '    switch (byte) {']
    lines += [f'    case {byte}: return {json.dumps(char, ensure_ascii=False)};'
              for byte, char in sorted(chars.items())]
    lines += ['    default: return "�";', '    }', '}', '']
    japanese = {value[0]: key for key, value in parse_charmap(vendor).items()
                if len(key) == 1 and len(value) == 1 and value[0] != 255}
    lines += ['inline const char* JapaneseNicknameGlyph(unsigned byte) {', '    switch (byte) {']
    lines += [f'    case {byte}: return {json.dumps(char, ensure_ascii=False)};'
              for byte, char in sorted(japanese.items())]
    lines += ['    default: return "�";', '    }', '}', '']
    return '\n'.join(lines)


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    expected = build()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text() != expected:
            raise SystemExit('R9 display catalog is stale')
    else:
        OUTPUT.write_text(expected)
